{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.programs.herdr;
  enabled = name: cfg.integrations.${name}.enable;

  mkIntegrationAsset =
    {
      name,
      source,
    }:
    pkgs.runCommand "herdr-${name}-integration-asset"
      {
        nativeBuildInputs = [ cfg.package ];
      }
      ''
        export HOME="$TMPDIR/home"
        export CLAUDE_CONFIG_DIR="$HOME/claude"
        export CODEX_HOME="$HOME/codex"

        mkdir -p "$CLAUDE_CONFIG_DIR" "$CODEX_HOME" "$HOME/.config/opencode"
        herdr integration install ${name}
        cp ${source} "$out"
      '';

  integrationAssets = {
    claude = mkIntegrationAsset {
      name = "claude";
      source = ''"$CLAUDE_CONFIG_DIR/hooks/herdr-agent-state.sh"'';
    };
    codex = mkIntegrationAsset {
      name = "codex";
      source = ''"$CODEX_HOME/herdr-agent-state.sh"'';
    };
    opencode = mkIntegrationAsset {
      name = "opencode";
      source = ''"$HOME/.config/opencode/plugins/herdr-agent-state.js"'';
    };
  };

  mkIntegrationOption = name: {
    enable = lib.mkEnableOption "Herdr's ${name} integration" // {
      description = ''
        Whether to configure Herdr's ${name} integration declaratively.
        The integration asset is generated by the selected Herdr package and
        referenced from the harness configuration managed by Home Manager.
      '';
    };
  };
in
{
  options.programs.herdr.integrations = {
    claude = mkIntegrationOption "Claude Code";
    codex = mkIntegrationOption "Codex";
    opencode = mkIntegrationOption "OpenCode";
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion =
          cfg.package != null
          || !(lib.any enabled [
            "claude"
            "codex"
            "opencode"
          ]);
        message = "programs.herdr.package must not be null when integrations are enabled";
      }
      {
        assertion = !(enabled "claude") || config.programs.claude-code.enable;
        message = "programs.herdr.integrations.claude requires programs.claude-code.enable";
      }
      {
        assertion = !(enabled "codex") || config.programs.codex.enable;
        message = "programs.herdr.integrations.codex requires programs.codex.enable";
      }
      {
        assertion = !(enabled "opencode") || config.programs.opencode.enable;
        message = "programs.herdr.integrations.opencode requires programs.opencode.enable";
      }
    ];

    programs.claude-code.settings.hooks.SessionStart = lib.mkIf (enabled "claude") (
      lib.mkAfter [
        {
          matcher = "*";
          hooks = [
            {
              type = "command";
              command = "bash '${integrationAssets.claude}' session";
              timeout = 10;
            }
          ];
        }
      ]
    );

    programs.codex = lib.mkIf (enabled "codex") {
      settings.features.hooks = true;
      hooks.SessionStart = lib.mkAfter [
        {
          hooks = [
            {
              type = "command";
              command = "bash '${integrationAssets.codex}' session";
              timeout = 10;
            }
          ];
        }
      ];
    };

    xdg.configFile."opencode/plugins/herdr-agent-state.js" = lib.mkIf (enabled "opencode") {
      source = integrationAssets.opencode;
    };
  };
}
